### ISSUE TITLE
Add get player runner function

### ISSUE THREAD

**Issue by timblegoorn** [cs481-ekh/f22-kitty-cat-studios#223]
References #220 

In this task I will keep track of the pointer to the player runner object in AISpawnerController and add a helper function that returns this pointer to quickly and efficiently grab the player.

**Comment by timblegoorn** [comment]
example usage in Runner.cpp: 
`((ARunner*)spawnController->GetPlayer())->isAI`

**Comment by timblegoorn** [comment]
Had a lot of trouble trying to figure out how to return the player as ARunner* instead of AActor*. As far as I can tell, it's not possible with the current implementation as Runner.h requires AISpawnerController and if AISpawnerController requires Runner, there's a circular declaration that doesn't work in C++ (as far as I know). So, that being said this still works but when calling get player here you will need to cast it to ARunner to access runner functions.

**Comment by ekhenderson** [comment]
You can do a "forward decl" of a class in cases like this. Essentially you tell the compiler a variable is a class but don't define it: class x;

That way you don't need to include the header file for class x.

See https://stackoverflow.com/questions/4757565/what-are-forward-declarations-in-c

**Comment by timblegoorn** [comment]
> 

Oh that's super neat! Thanks for sharing that.

**Comment by timblegoorn** [comment]
> You can do a "forward decl" of a class in cases like this. Essentially you tell the compiler a variable is a class but don't define it: class x;
> 
> That way you don't need to include the header file for class x.
> 
> See https://stackoverflow.com/questions/4757565/what-are-forward-declarations-in-c

Oh that's super neat! Thanks for sharing that.
